<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('InstantHistory', 'doctrine');

/**
 * BaseInstantHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $movie_id
 * @property integer $seektime
 * @property integer $did_finish
 * 
 * @method integer        getUserId()     Returns the current record's "user_id" value
 * @method integer        getMovieId()    Returns the current record's "movie_id" value
 * @method integer        getSeektime()   Returns the current record's "seektime" value
 * @method integer        getDidFinish()  Returns the current record's "did_finish" value
 * @method InstantHistory setUserId()     Sets the current record's "user_id" value
 * @method InstantHistory setMovieId()    Sets the current record's "movie_id" value
 * @method InstantHistory setSeektime()   Sets the current record's "seektime" value
 * @method InstantHistory setDidFinish()  Sets the current record's "did_finish" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInstantHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('instant_history');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('movie_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('seektime', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('did_finish', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}