<?php

/**
 * BaseUserQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $movie_id
 * @property integer $position
 * @property string $format
 * 
 * @method integer   getUserId()   Returns the current record's "user_id" value
 * @method integer   getMovieId()  Returns the current record's "movie_id" value
 * @method integer   getPosition() Returns the current record's "position" value
 * @method string    getFormat()   Returns the current record's "format" value
 * @method UserQueue setUserId()   Sets the current record's "user_id" value
 * @method UserQueue setMovieId()  Sets the current record's "movie_id" value
 * @method UserQueue setPosition() Sets the current record's "position" value
 * @method UserQueue setFormat()   Sets the current record's "format" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserQueue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_queue');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('movie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('format', 'string', 3, array(
             'type' => 'string',
             'primary' => true,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}