<?php

/**
 * BasePerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property Doctrine_Collection $Credits
 * @property Doctrine_Collection $Movies
 * @property Doctrine_Collection $MovieCreditPerson
 * 
 * @method string              getFirstName()         Returns the current record's "first_name" value
 * @method string              getLastName()          Returns the current record's "last_name" value
 * @method Doctrine_Collection getCredits()           Returns the current record's "Credits" collection
 * @method Doctrine_Collection getMovies()            Returns the current record's "Movies" collection
 * @method Doctrine_Collection getMovieCreditPerson() Returns the current record's "MovieCreditPerson" collection
 * @method Person              setFirstName()         Sets the current record's "first_name" value
 * @method Person              setLastName()          Sets the current record's "last_name" value
 * @method Person              setCredits()           Sets the current record's "Credits" collection
 * @method Person              setMovies()            Sets the current record's "Movies" collection
 * @method Person              setMovieCreditPerson() Sets the current record's "MovieCreditPerson" collection
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person');
        $this->hasColumn('first_name', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('last_name', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Credit as Credits', array(
             'refClass' => 'movieCreditPerson',
             'local' => 'person_id',
             'foreign' => 'credit_id'));

        $this->hasMany('Movie as Movies', array(
             'refClass' => 'movieCreditPerson',
             'local' => 'person_id',
             'foreign' => 'movie_id'));

        $this->hasMany('MovieCreditPerson', array(
             'local' => 'id',
             'foreign' => 'person_id'));
    }
}