<?php

/**
 * BaseRating
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $movie_id
 * @property integer $rating
 * 
 * @method integer getUserId()   Returns the current record's "user_id" value
 * @method integer getMovieId()  Returns the current record's "movie_id" value
 * @method integer getRating()   Returns the current record's "rating" value
 * @method Rating  setUserId()   Sets the current record's "user_id" value
 * @method Rating  setMovieId()  Sets the current record's "movie_id" value
 * @method Rating  setRating()   Sets the current record's "rating" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRating extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rating');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('movie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('rating', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}