<?php

/**
 * BaseShippingMethod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property float $cost
 * 
 * @method integer        getId()   Returns the current record's "id" value
 * @method string         getName() Returns the current record's "name" value
 * @method float          getCost() Returns the current record's "cost" value
 * @method ShippingMethod setId()   Sets the current record's "id" value
 * @method ShippingMethod setName() Sets the current record's "name" value
 * @method ShippingMethod setCost() Sets the current record's "cost" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShippingMethod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shipping_method');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('cost', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}