<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('States', 'doctrine');

/**
 * BaseStates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $abbr
 * @property decimal $sales_tax
 * @property integer $charge_tax
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getAbbr()       Returns the current record's "abbr" value
 * @method decimal getSalesTax()   Returns the current record's "sales_tax" value
 * @method integer getChargeTax()  Returns the current record's "charge_tax" value
 * @method States  setId()         Sets the current record's "id" value
 * @method States  setName()       Sets the current record's "name" value
 * @method States  setAbbr()       Sets the current record's "abbr" value
 * @method States  setSalesTax()   Sets the current record's "sales_tax" value
 * @method States  setChargeTax()  Sets the current record's "charge_tax" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStates extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('states');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('abbr', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('sales_tax', 'decimal', 7, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0.000000',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 7,
             'scale' => '6',
             ));
        $this->hasColumn('charge_tax', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}