<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ListLookup', 'doctrine');

/**
 * BaseListLookup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $list_id
 * @property integer $movie_id
 * 
 * @method integer    getListId()   Returns the current record's "list_id" value
 * @method integer    getMovieId()  Returns the current record's "movie_id" value
 * @method ListLookup setListId()   Sets the current record's "list_id" value
 * @method ListLookup setMovieId()  Sets the current record's "movie_id" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListLookup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('list_lookup');
        $this->hasColumn('list_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('movie_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}