<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SuggestCache', 'doctrine');

/**
 * BaseSuggestCache
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $list_type
 * @property integer $list_id
 * @property float $ratio
 * 
 * @method integer      getId()        Returns the current record's "id" value
 * @method integer      getUserId()    Returns the current record's "user_id" value
 * @method integer      getListType()  Returns the current record's "list_type" value
 * @method integer      getListId()    Returns the current record's "list_id" value
 * @method float        getRatio()     Returns the current record's "ratio" value
 * @method SuggestCache setId()        Sets the current record's "id" value
 * @method SuggestCache setUserId()    Sets the current record's "user_id" value
 * @method SuggestCache setListType()  Sets the current record's "list_type" value
 * @method SuggestCache setListId()    Sets the current record's "list_id" value
 * @method SuggestCache setRatio()     Sets the current record's "ratio" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSuggestCache extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('suggest_cache');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('list_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('list_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ratio', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}