<?php

/**
 * BaseMovieCreditPerson
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $movie_id
 * @property integer $credit_id
 * @property integer $person_id
 * @property Movie $Movie
 * @property Credit $Credit
 * @property Person $Person
 * 
 * @method integer           getMovieId()   Returns the current record's "movie_id" value
 * @method integer           getCreditId()  Returns the current record's "credit_id" value
 * @method integer           getPersonId()  Returns the current record's "person_id" value
 * @method Movie             getMovie()     Returns the current record's "Movie" value
 * @method Credit            getCredit()    Returns the current record's "Credit" value
 * @method Person            getPerson()    Returns the current record's "Person" value
 * @method MovieCreditPerson setMovieId()   Sets the current record's "movie_id" value
 * @method MovieCreditPerson setCreditId()  Sets the current record's "credit_id" value
 * @method MovieCreditPerson setPersonId()  Sets the current record's "person_id" value
 * @method MovieCreditPerson setMovie()     Sets the current record's "Movie" value
 * @method MovieCreditPerson setCredit()    Sets the current record's "Credit" value
 * @method MovieCreditPerson setPerson()    Sets the current record's "Person" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMovieCreditPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('movie_credit_person');
        $this->hasColumn('movie_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('credit_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('person_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Movie', array(
             'local' => 'movie_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Credit', array(
             'local' => 'credit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Person', array(
             'local' => 'person_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}