<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserInstantAuth', 'doctrine');

/**
 * BaseUserInstantAuth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $movie_id
 * @property string $hash
 * @property timestamp $authtime
 * 
 * @method integer         getUserId()   Returns the current record's "user_id" value
 * @method integer         getMovieId()  Returns the current record's "movie_id" value
 * @method string          getHash()     Returns the current record's "hash" value
 * @method timestamp       getAuthtime() Returns the current record's "authtime" value
 * @method UserInstantAuth setUserId()   Sets the current record's "user_id" value
 * @method UserInstantAuth setMovieId()  Sets the current record's "movie_id" value
 * @method UserInstantAuth setHash()     Sets the current record's "hash" value
 * @method UserInstantAuth setAuthtime() Sets the current record's "authtime" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserInstantAuth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_instant_auth');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('movie_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('hash', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('authtime', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}