<?php

/**
 * BasePlanTypes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $type
 * @property string $name
 * @property float $monthly_cost
 * @property string $description
 * @property integer $active
 * @property integer $instant_minutes
 * @property integer $dvds_out
 * @property integer $dvds_per_month
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method string    getType()            Returns the current record's "type" value
 * @method string    getName()            Returns the current record's "name" value
 * @method float     getMonthlyCost()     Returns the current record's "monthly_cost" value
 * @method string    getDescription()     Returns the current record's "description" value
 * @method integer   getActive()          Returns the current record's "active" value
 * @method integer   getInstantMinutes()  Returns the current record's "instant_minutes" value
 * @method integer   getDvdsOut()         Returns the current record's "dvds_out" value
 * @method integer   getDvdsPerMonth()    Returns the current record's "dvds_per_month" value
 * @method PlanTypes setId()              Sets the current record's "id" value
 * @method PlanTypes setType()            Sets the current record's "type" value
 * @method PlanTypes setName()            Sets the current record's "name" value
 * @method PlanTypes setMonthlyCost()     Sets the current record's "monthly_cost" value
 * @method PlanTypes setDescription()     Sets the current record's "description" value
 * @method PlanTypes setActive()          Sets the current record's "active" value
 * @method PlanTypes setInstantMinutes()  Sets the current record's "instant_minutes" value
 * @method PlanTypes setDvdsOut()         Sets the current record's "dvds_out" value
 * @method PlanTypes setDvdsPerMonth()    Sets the current record's "dvds_per_month" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanTypes extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plan_types');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('type', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('monthly_cost', 'float', 5, array(
             'type' => 'float',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('instant_minutes', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('dvds_out', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('dvds_per_month', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}