<?php

/**
 * BaseCiSessions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $session_id
 * @property string $ip_address
 * @property string $user_agent
 * @property integer $last_activity
 * @property string $user_data
 * 
 * @method string     getSessionId()     Returns the current record's "session_id" value
 * @method string     getIpAddress()     Returns the current record's "ip_address" value
 * @method string     getUserAgent()     Returns the current record's "user_agent" value
 * @method integer    getLastActivity()  Returns the current record's "last_activity" value
 * @method string     getUserData()      Returns the current record's "user_data" value
 * @method CiSessions setSessionId()     Sets the current record's "session_id" value
 * @method CiSessions setIpAddress()     Sets the current record's "ip_address" value
 * @method CiSessions setUserAgent()     Sets the current record's "user_agent" value
 * @method CiSessions setLastActivity()  Sets the current record's "last_activity" value
 * @method CiSessions setUserData()      Sets the current record's "user_data" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCiSessions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ci_sessions');
        $this->hasColumn('session_id', 'string', 40, array(
             'type' => 'string',
             'primary' => true,
             'length' => 40,
             ));
        $this->hasColumn('ip_address', 'string', 16, array(
             'type' => 'string',
             'default' => '0',
             'notnull' => true,
             'length' => 16,
             ));
        $this->hasColumn('user_agent', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('last_activity', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'default' => '0',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_data', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}