<?php

/**
 * BaseMovieForsale
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $movie_id
 * @property decimal $price
 * @property string $format
 * @property integer $qty
 * @property integer $active
 * @property integer $backordered
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getMovieId()     Returns the current record's "movie_id" value
 * @method decimal      getPrice()       Returns the current record's "price" value
 * @method string       getFormat()      Returns the current record's "format" value
 * @method integer      getQty()         Returns the current record's "qty" value
 * @method integer      getActive()      Returns the current record's "active" value
 * @method integer      getBackordered() Returns the current record's "backordered" value
 * @method MovieForsale setId()          Sets the current record's "id" value
 * @method MovieForsale setMovieId()     Sets the current record's "movie_id" value
 * @method MovieForsale setPrice()       Sets the current record's "price" value
 * @method MovieForsale setFormat()      Sets the current record's "format" value
 * @method MovieForsale setQty()         Sets the current record's "qty" value
 * @method MovieForsale setActive()      Sets the current record's "active" value
 * @method MovieForsale setBackordered() Sets the current record's "backordered" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMovieForsale extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('movie_forsale');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('movie_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('price', 'decimal', 4, array(
             'type' => 'decimal',
             'notnull' => true,
             'length' => 4,
             'scale' => '2',
             ));
        $this->hasColumn('format', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3,
             ));
        $this->hasColumn('qty', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('active', 'integer', 1, array(
             'type' => 'integer',
             'default' => '1',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('backordered', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}