<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SuggestCacheStatus', 'doctrine');

/**
 * BaseSuggestCacheStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $list_type
 * @property timestamp $lastcheck
 * @property integer $countsince
 * @property integer $numrows
 * 
 * @method integer            getUserId()     Returns the current record's "user_id" value
 * @method integer            getListType()   Returns the current record's "list_type" value
 * @method timestamp          getLastcheck()  Returns the current record's "lastcheck" value
 * @method integer            getCountsince() Returns the current record's "countsince" value
 * @method integer            getNumrows()    Returns the current record's "numrows" value
 * @method SuggestCacheStatus setUserId()     Sets the current record's "user_id" value
 * @method SuggestCacheStatus setListType()   Sets the current record's "list_type" value
 * @method SuggestCacheStatus setLastcheck()  Sets the current record's "lastcheck" value
 * @method SuggestCacheStatus setCountsince() Sets the current record's "countsince" value
 * @method SuggestCacheStatus setNumrows()    Sets the current record's "numrows" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSuggestCacheStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('suggest_cache_status');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('list_type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('lastcheck', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('countsince', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('numrows', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}