<?php

/**
 * BaseCredit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Movies
 * @property Doctrine_Collection $MovieCreditPerson
 * @property Doctrine_Collection $People
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getDescription()       Returns the current record's "description" value
 * @method Doctrine_Collection getMovies()            Returns the current record's "Movies" collection
 * @method Doctrine_Collection getMovieCreditPerson() Returns the current record's "MovieCreditPerson" collection
 * @method Doctrine_Collection getPeople()            Returns the current record's "People" collection
 * @method Credit              setName()              Sets the current record's "name" value
 * @method Credit              setDescription()       Sets the current record's "description" value
 * @method Credit              setMovies()            Sets the current record's "Movies" collection
 * @method Credit              setMovieCreditPerson() Sets the current record's "MovieCreditPerson" collection
 * @method Credit              setPeople()            Sets the current record's "People" collection
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCredit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('credit');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Movie as Movies', array(
             'refClass' => 'movieCreditPerson',
             'local' => 'credit_id',
             'foreign' => 'movie_id'));

        $this->hasMany('MovieCreditPerson', array(
             'local' => 'id',
             'foreign' => 'credit_id'));

        $this->hasMany('Person as People', array(
             'refClass' => 'movieCreditPerson',
             'local' => 'credit_id',
             'foreign' => 'person_id'));
    }
}