<?php

/**
 * BaseListValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $type
 * @property date $dob
 * @property string $location
 * 
 * @method integer    getId()          Returns the current record's "id" value
 * @method string     getName()        Returns the current record's "name" value
 * @method string     getDescription() Returns the current record's "description" value
 * @method integer    getType()        Returns the current record's "type" value
 * @method date       getDob()         Returns the current record's "dob" value
 * @method string     getLocation()    Returns the current record's "location" value
 * @method ListValues setId()          Sets the current record's "id" value
 * @method ListValues setName()        Sets the current record's "name" value
 * @method ListValues setDescription() Sets the current record's "description" value
 * @method ListValues setType()        Sets the current record's "type" value
 * @method ListValues setDob()         Sets the current record's "dob" value
 * @method ListValues setLocation()    Sets the current record's "location" value
 * 
 * @package    dukaan
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListValues extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('list_values');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 75, array(
             'type' => 'string',
             'default' => '0',
             'notnull' => true,
             'length' => 75,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('type', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('dob', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('location', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}