# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

user:
  class: sfDoctrineRouteCollection
  options:
    prefix_path: /user
    model:       sfGuardUser
    module:      user

permission:
  class: sfDoctrineRouteCollection
  options:
    prefix_path: /permission
    model:       sfGuardPermission
    module:      permission

group:
  class: sfDoctrineRouteCollection
  options:
    prefix_path: /group
    model:       sfGuardGroup
    module:      group

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
