<?php

/**
 * CiSessionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CiSessionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CiSessionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CiSessions');
    }
}