<?php

/**
 * CreditTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CreditTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CreditTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Credit');
    }
}