<?php

/**
 * InstantHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstantHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstantHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstantHistory');
    }
}