<?php

/**
 * ListValuesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListValuesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListValuesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListValues');
    }
}