<?php

/**
 * ListLookupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListLookupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListLookupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListLookup');
    }
}