<?php

/**
 * ListTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListTypes');
    }
}