<?php

/**
 * MovieForrentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovieForrentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovieForrentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MovieForrent');
    }
}