<?php

/**
 * MovieCreditPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovieCreditPersonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovieCreditPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MovieCreditPerson');
    }
}