<?php

/**
 * MovieForstreamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovieForstreamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovieForstreamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MovieForstream');
    }
}