<?php

/**
 * MovieForsaleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MovieForsaleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MovieForsaleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MovieForsale');
    }
}