<?php

/**
 * PlanTypesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanTypesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanTypesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanTypes');
    }
}