<?php

/**
 * RatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RatingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RatingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rating');
    }
}