<?php

/**
 * ShippingMethodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShippingMethodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShippingMethodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShippingMethod');
    }
}