<?php

/**
 * StatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('States');
    }
}