<?php

/**
 * SuggestCacheTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuggestCacheTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuggestCacheTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SuggestCache');
    }
}