<?php

/**
 * SuggestCacheStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuggestCacheStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuggestCacheStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SuggestCacheStatus');
    }
}