<?php

/**
 * Top50Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Top50Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Top50Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Top50');
    }
}