<?php

/**
 * UserRentalsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserRentalsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserRentalsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserRentals');
    }
}