<?php

/**
 * UserInstantAuthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserInstantAuthTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserInstantAuthTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserInstantAuth');
    }
}