<?php

/**
 * UserQueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserQueue');
    }
}