<?php

/**
 * UserSubscriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSubscriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSubscriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSubscription');
    }
}