<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/01 12:33:58

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dukaan',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
