<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/04/01 12:39:49
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
