Address:
  columns:
    id:
      type:          integer(4)
      primary:       true
      autoincrement: true
    user_id:
      type:    integer(4)
      default: '0'
      notnull: true
    is_billing:
      type:    integer(1)
      default: '0'
      notnull: true
    name_person:
      type:    string(60)
      default: '0'
      notnull: true
    name_company:
      type:    string(60)
      default: '0'
      notnull: true
    address1: string(60)
    address2: string(60)
    city:     string(60)
    state:    string(2)
    zip:      string(12)
    phone_1:  string(16)
    phone_2:  string(16)
    phone_3:  string(16)

CiSessions:
  columns:
    session_id:
      type:    string(40)
      primary: true
    ip_address:
      type:    string(16)
      default: '0'
      notnull: true
    user_agent:
      type: string(50)
      notnull: true
    last_activity:
      type:     integer(4)
      unsigned: true
      default:  '0'
      notnull:  true
    user_data:
      type:    string
      notnull: true

InstantHistory:
  columns:
    user_id:
      type: integer(4)
      primary: true
    movie_id:
      type: integer(4)
      primary: true
    seektime: integer(4)
    did_finish: integer(4)

ListLookup:
  columns:
    list_id:
      type: integer(4)
      primary: true
    movie_id:
      type: integer(4)
      primary: true

ListTypes:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    type:
      type: string(50)
      default: ''
      notnull: true

ListValues:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(75)
      default: '0'
      notnull: true
    description: string
    type:
      type: integer(4)
      notnull: true
    dob: date(25)
    location: string(100)

Log:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    action_type:
      type: string(10)
      default: '0'
      notnull: true
    user_id:
      type: integer(4)
      default: '0'
      notnull: true
    movie_id:
      type: integer(4)
      default: '0'
      notnull: true
    detailtext:
      type: string
      notnull: true

Movie:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    title:
      type: string(75)
      default: '0'
      notnull: true
    year:
      type: integer(4)
      default: '0'
      notnull: true
    description: string
    can_rent:
      type: integer(1)
      default: '0'
      notnull: true
    can_buy:
      type: integer(1)
      default: '0'
      notnull: true
    can_stream:
      type: integer(1)
      default: '0'
      notnull: true
    rating_average:
      type: float
      default: '2.5'
      notnull: true
    rating_count:
      type: integer(2)
      default: '0'
      notnull: true
    film_type:
      type: string(1)
      default: B
    mpaa: string(5)
    runtime:
      type: integer(4)
      default: '0'
    active:
      type: integer(2)
      default: '0'
      notnull: true
    date_added:
      type: timestamp(25)
      notnull: true

MovieForrent:
  columns:
    id:
      type:          integer(4)
      primary:       true
      autoincrement: true
    movie_id:
      type:    integer(4)
      notnull: true
    price:
      type:    decimal(4, 2)
      notnull: true
    format:
      type:    string(3)
      notnull: true
    active:
      type:    integer(1)
      notnull: true

MovieForsale:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    movie_id:
      type: integer(4)
      notnull: true
    price:
      type:  decimal(4, 2)
      notnull: true
    format:
      type: string(3)
      notnull: true
    qty: integer(4)
    active:
      type: integer(1)
      default: '1'
      notnull: true
    backordered:
      type: integer(1)
      default: '0'
      notnull: true

MovieForstream:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    movie_id:
      type: integer(4)
      default: '0'
    bucket_name:
      type: string(128)
      default: '0'
    domain_name:
      type: string(128)
      default: '0'
    distribution_id:
      type: string(128)
      default: '0'

PlanTypes:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    type:
      type: string(50)
      notnull: true
    name:
      type: string(50)
      notnull: true
    monthly_cost:
      type: float(5)
      notnull: true
    description:
      type: string
      notnull: true
    active:
      type: integer(1)
      default: '1'
      notnull: true
    instant_minutes:
      type: integer(4)
      notnull: true
    dvds_out:
      type: integer(4)
      notnull: true
    dvds_per_month:
      type: integer(4)
      notnull: true

Rating:
  columns:
    user_id:
      type: integer(4)
      primary: true
    movie_id:
      type: integer(4)
      primary: true
    rating:
      type: integer(4)
      notnull: true

ShippingMethod:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(50)
      notnull: true
    cost:
      type: float
      notnull: true

States:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    abbr:
      type: string(2)
      notnull: true
    sales_tax:
      type:    decimal(7,6)
      default: '0.000000'
      notnull: true
    charge_tax:
      type:    integer(1)
      default: '0'
      notnull: true

SuggestCache:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    user_id:
      type: integer(4)
      default: '0'
    list_type:
      type: integer(4)
      default: '0'
    list_id:
      type: integer(4)
      default: '0'
    ratio:
      type: float
      default: '0'

SuggestCacheStatus:
  columns:
    user_id:
      type: integer(4)
      primary: true
    list_type:
      type: integer(4)
      primary: true
    lastcheck:
      type: timestamp(25)
      notnull: true
    countsince:
      type: integer(4)
      notnull: true
    numrows:
      type: integer(4)
      notnull: true

Top50:
  columns:
    movie_id:
      type: integer(4)
      default: '0'
      notnull: true
    position:
      type: integer(4)
      primary: true
      autoincrement: true
    last_position: integer(4)

User:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    email:
      type: string(60)
      default: '0'
      notnull: true
    password:
      type: string(32)
      notnull: true
    firstname:
      type: string(60)
      default: '0'
      notnull: true
    lastname:
      type: string(60)
      default: '0'
      notnull: true
    company:
      type: string(60)
      default: '0'
      notnull: true
    had_trial:
      type: integer(1)
      default: '0'
      notnull: true
    trial_expire_date: timestamp(25)
    dob: timestamp(25)
    gender:
      type: string(1)
      default: '0'
    primary_address:
      type: integer(4)
      default: '0'
      notnull: true
    is_admin: integer(1)
  relations:
    UserSubscription:
      local: id
      foreign: user_id
      type: many

UserInstantAuth:
  columns:
    user_id:
      type: integer(4)
      primary: true
    movie_id:
      type: integer(4)
      notnull: true
    hash:
      type: string(32)
      notnull: true
    authtime:
      type: timestamp(25)
      notnull: true

UserQueue:
  columns:
    user_id:
      type: integer(4)
      primary: true
    movie_id:
      type: integer(4)
      primary: true
    position:
      type: integer(4)
      notnull: true
    format:
      type: string(3)
      primary: true

UserRentals:
  columns:
    user_id:
      type: integer(4)
      primary: true
    movie_id:
      type: integer(4)
      primary: true
    format:
      type: string(50)
      notnull: true
    out_now:
      type: integer(1)
      notnull: true
    date_rented:
      type: timestamp(25)
      notnull: true
    date_returned:
      type: timestamp(25)
      default: '0000-00-00 00:00:00'
      notnull: true

UserSubscription:
  columns:
    user_id:
      type: integer(4)
      primary: true
    plan_id:
      type: integer(4)
      notnull: true
    start_date:
      type: timestamp(25)
      notnull: true
    renewal_date:
      type: timestamp(25)
      default: '0000-00-00 00:00:00'
      notnull: true
    monthly_cost:
      type: float(5)
      notnull: true
    dvds_this_month:
      type: integer(4)
      notnull: true
    minutes_remaining:
      type: integer(4)
      notnull: true
  relations:
    User:
      local: user_id
      foreign: id
      type: one

MovieCreditPerson:
  columns:
    movie_id:
      type: integer(4)
      primary: true
    credit_id:
      type: integer
      primary: true
    person_id:
      type: integer
      primary: true
  relations:
    Movie:
      onDelete: CASCADE
    Credit:
      onDelete: CASCADE
    Person:
      onDelete: CASCADE

Credit:
  columns:
    name: string(255)
    description: string(255)
  relations:
    Movies:
      class: Movie
      refClass: movieCreditPerson
      local: credit_id
      foreign: movie_id
      foreignAlias: Credits

Person:
  columns:
    first_name: string(20)
    last_name: string(20)
  relations:
    Credits:
      class: Credit
      refClass: movieCreditPerson
      local: person_id
      foreign: credit_id
      foreignAlias: People
    Movies:
      class: Movie
      refClass: movieCreditPerson
      local: person_id
      foreign: movie_id
      foreignAlias: People